wwWallet/wallet-ecosystem

- ecosystem.js
Companion PR of gunet/wallet-backend-server#24, but also depends on gunet/wallet-ecosystem#20 because of the changes to `--workdir` and `NODE_PATH`.
> Run database init automatically

- wallet-enterprise-configurations/acme-verifier/src/configuration/verifier/VerifierConfigurationService.ts
Added more presentation definitions for ACME verifier
> Additional presentation definitions for ACME

- wallet-enterprise-configurations/acme-verifier/public/styles/styles.css
- wallet-enterprise-configurations/acme-verifier/views/header.pug
- wallet-enterprise-configurations/acme-verifier/views/verifier/QR.pug
This pull request resolves the issue related to the non-responsiveness of the Acme Verifier on small screens, particularly mobile devices.
> Responsive Design Fixes

- wallet-enterprise-configurations/acme-verifier/config/config.development.ts
- wallet-enterprise-configurations/acme-verifier/views/verifier/QR.pug
- wallet-enterprise-configurations/diploma-issuer/config/config.development.ts
- wallet-enterprise-configurations/diploma-issuer/src/configuration/authentication/VIDAuthenticationComponent.ts
- wallet-enterprise-configurations/ehic-issuer/config/config.development.ts
- wallet-enterprise-configurations/vid-issuer/config/config.development.ts
This PR is linked with https://github.com/wwWallet/wallet-enterprise/pull/18
> Configurable open with wwwallet button

- docker-compose.template.yml
This PR will increase security in case the development environment is set up on a machine with a public IP address.
> Prevent outside db connections

- wallet-enterprise-configurations/acme-verifier/public/styles/styles.css
- wallet-enterprise-configurations/acme-verifier/src/configuration/locale.ts
- wallet-enterprise-configurations/acme-verifier/src/configuration/verifier/VerifierConfigurationService.ts
- wallet-enterprise-configurations/acme-verifier/views/verifier/public_definitions.pug
- wallet-enterprise-configurations/acme-verifier/views/verifier/success.pug
Related with https://github.com/wwWallet/wallet-enterprise/pull/28
> Verifier revamp

- wallet-enterprise-configurations/acme-verifier/views/verifier/QR.pug
Related PRs:
- https://github.com/wwWallet/wallet-enterprise/pull/55
> replaced automatic form submission with polling for verification status

- wallet-enterprise-configurations/vid-issuer/src/configuration/authentication/LocalAuthenticationComponent.ts
Replaced old local authentication component with new one which is same with the one used for the diploma and ehic issuer
This PR solves the open issue:
- https://github.com/wwWallet/wallet-enterprise/issues/56
> Re-request authentication on each authorization request sent to the VID Issuer

- wallet-enterprise-configurations/acme-verifier/config/index.ts
- wallet-enterprise-configurations/ehic-issuer/config/index.ts
- wallet-enterprise-configurations/vid-issuer/config/index.ts
Linked PRs:
- https://github.com/wwWallet/wallet-frontend/pull/415
- https://github.com/wwWallet/wallet-enterprise/pull/68
> OID4VP: Improvements

- wallet-enterprise-configurations/acme-verifier/src/configuration/verifier/VerifierConfigurationService.ts
- wallet-enterprise-configurations/diploma-issuer/src/configuration/verifier/VerifierConfigurationService.ts
- wallet-enterprise-configurations/ehic-issuer/src/configuration/verifier/VerifierConfigurationService.ts
- wallet-enterprise-configurations/vid-issuer/src/configuration/verifier/VerifierConfigurationService.ts
Depends on:
- https://github.com/wwWallet/wallet-enterprise/pull/82
> Implement new functions of VerifierConfigurationInterface

- wallet-enterprise-configurations/acme-verifier/src/configuration/locale.ts
- wallet-enterprise-configurations/diploma-issuer/src/configuration/issuerSigner.ts
- wallet-enterprise-configurations/ehic-issuer/src/configuration/issuerSigner.ts
- wallet-enterprise-configurations/vid-issuer/src/configuration/issuerSigner.ts
Related PRs:
- https://github.com/wwWallet/wallet-enterprise/pull/88
- https://github.com/wwWallet/wallet-frontend/pull/496
> Fix credential token expiry

- wallet-enterprise-configurations/issuer/src/configuration/locale.ts
Related PRs:
- https://github.com/wwWallet/wallet-enterprise/pull/118
> Added interop profiles on landing page

- wallet-enterprise-configurations/issuer/src/configuration/SupportedCredentialsConfiguration/PIDSupportedCredentialSdJwtVCDM.ts
> Add birthdate in sd-jwt disclosure frame

- wallet-enterprise-configurations/issuer/src/configuration/locale.ts
Related with https://github.com/wwWallet/wallet-enterprise/pull/126
> Αdd locale header sd-jwt vc type metadata

- wallet-enterprise-configurations/issuer/src/configuration/locale.ts
Reverts wwWallet/wallet-ecosystem#160
> Revert "Αdd locale header sd-jwt vc type metadata"

- wallet-enterprise-configurations/acme-verifier/src/configuration/verifier/VerifierConfigurationService.ts
- Add combined presentation definition of PID (ARF 1.8) and Bachelor
- Add PID ARF 1.5
> Add combined presentation for pid and bachelor, add pid 1.5

- wallet-enterprise-configurations/issuer/src/configuration/SupportedCredentialsConfiguration/EHICSupportedCredentialSdJwtVCDM.ts
- wallet-enterprise-configurations/issuer/src/configuration/SupportedCredentialsConfiguration/EdiplomasBlueprintSdJwtVCDM.ts
- wallet-enterprise-configurations/issuer/src/configuration/SupportedCredentialsConfiguration/PIDSupportedCredentialMsoMdoc.ts
- wallet-enterprise-configurations/issuer/src/configuration/SupportedCredentialsConfiguration/PIDSupportedCredentialSdJwtVCDM.ts
- wallet-enterprise-configurations/issuer/src/configuration/SupportedCredentialsConfiguration/PIDSupportedCredentialSdJwtVCDM_1_5.ts
- wallet-enterprise-configurations/issuer/src/configuration/SupportedCredentialsConfiguration/PIDSupportedCredentialSdJwtVCDM_1_5_VC.ts
- wallet-enterprise-configurations/issuer/src/configuration/SupportedCredentialsConfiguration/PIDSupportedCredentialSdJwtVCDM_VC.ts
- wallet-enterprise-configurations/issuer/src/configuration/SupportedCredentialsConfiguration/PorSupportedCredentialSdJwt.ts
- wallet-enterprise-configurations/issuer/src/configuration/main.ts
- Allow multiple configurations with the same vct
- change display names
> Add vc+sd-jwt configuration

- wallet-enterprise-configurations/acme-verifier/src/configuration/verifier/VerifierConfigurationService.ts
> Make presentation definitions RFC 9535 compliant

- wallet-enterprise-configurations/issuer/src/configuration/issuerSigner.ts
See https://github.com/wwWallet/wallet-enterprise/pull/179 and https://github.com/wwWallet/wallet-enterprise/issues/178
> Utilization of Disclosure Frame object during sdjwt issuance

- wallet-enterprise-configurations/issuer/src/configuration/SupportedCredentialsConfiguration/PorSupportedCredentialSdJwt.ts
- wallet-enterprise-configurations/issuer/src/configuration/SupportedCredentialsConfiguration/schema/pda1Schema.ts
- wallet-enterprise-configurations/issuer/src/configuration/SupportedCredentialsConfiguration/schema/porSchema.ts
- wallet-enterprise-configurations/issuer/src/configuration/SupportedCredentialsConfiguration/typeMetadata/pda1Metadata.ts
- wallet-enterprise-configurations/issuer/src/configuration/SupportedCredentialsConfiguration/typeMetadata/porMetadata.ts
- wallet-enterprise-configurations/issuer/src/configuration/locale.ts
Changed landing page links for issuer
> Populated typeMetadata and schema for pda1 and por

- ecosystem.js
The purpose of this PR is to provide a way for building images from a MacOS operating system
> Use docker buildx instead of docker build
